// MODULE: agents-rules.test.ts - Epic 60.4: the rules master, per-harness renderings, link-safe install transactions, restore and probes
import { execFile } from 'node:child_process'
import { chmodSync, existsSync, lstatSync, mkdirSync, mkdtempSync, readFileSync, readlinkSync, realpathSync, rmSync, symlinkSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { sha256 } from '../../bin/agents-roster.mjs'
import { readValidRoster } from '../../bin/agents-state.mjs'
import {
  TEAM_LIMIT_BYTES, checkTargets, importedMaster, installRules, lastProbes, masterHistory, parseMaster, probe, probeInspector, readMaster, render, restoreTransaction, teamExpansion, writeMaster
} from '../../bin/agents-rules.mjs'
import { approveRoster } from '../main/agents-approval'

const CLI = fileURLToPath(new URL('../../bin/bmn', import.meta.url))
const EXAMPLE = readFileSync(fileURLToPath(new URL('./test-fixtures/agents/roster-example.md', import.meta.url)), 'utf8')
const MASTER = `# Global rules

Plain rule for everyone.

<!-- bmn:shareable -->
## How to talk
Answer first, plainly.
<!-- /bmn:shareable -->

## Team
<!-- bmn:team -->

<!-- bmn:harness opencode -->
## OpenCode
OpenCode-only rule.
<!-- /bmn:harness -->

<!-- bmn:harness claude codex -->
PRIVATE-SENTINEL: a rule only High routes may see.
<!-- /bmn:harness -->
`

let home: string
let stubs: string
let env: Record<string, string>
const savedHome = process.env.HOME

function stub(name: string, body: string): void {
  writeFileSync(join(stubs, name), `#!/bin/sh\n${body}\n`)
  chmodSync(join(stubs, name), 0o755)
}

function writeMasterFile(text = MASTER): void {
  mkdirSync(join(home, '.config/bmn/agents'), { recursive: true })
  writeFileSync(join(home, '.config/bmn/agents/global-rules.md'), text)
}

function approve(text = EXAMPLE): void {
  mkdirSync(join(home, '.config/bmn/agents'), { recursive: true })
  writeFileSync(join(home, '.config/bmn/agents/roster.md'), text)
  let generation: number | null
  try {
    generation = JSON.parse(readFileSync(join(home, '.config/bmn/agents/state/current'), 'utf8')).generation
  } catch {
    generation = null
  }
  approveRoster({ generation, fileHash: readValidRoster().hash })
}

beforeEach(() => {
  home = realpathSync(mkdtempSync(join(tmpdir(), 'bmn-rules-')))
  process.env.HOME = home
  stubs = join(home, 'stubs')
  mkdirSync(stubs)
  stub('codex', 'echo "codex-cli 0.161.0"')
  stub('claude', 'echo "2.1.295 (Claude Code)"')
  env = { HOME: home, PATH: `${stubs}:/usr/bin:/bin` }
  approve()
  writeMasterFile()
})

afterEach(() => {
  process.env.HOME = savedHome
  rmSync(home, { recursive: true, force: true })
})

const target = {
  claude: () => join(home, '.claude/CLAUDE.md'),
  codex: () => join(home, '.codex/AGENTS.md'),
  opencode: () => join(home, '.config/opencode/AGENTS.md'),
  cursor: () => join(home, '.cursor/rules/bmn-global-rules.mdc')
}

function generation() {
  return JSON.parse(readFileSync(join(home, `.config/bmn/agents/state/generations/${String(JSON.parse(readFileSync(join(home, '.config/bmn/agents/state/current'), 'utf8')).generation).padStart(6, '0')}.json`), 'utf8'))
}

describe('the master (60.4 AC1)', () => {
  it.each([
    ['an unknown harness', '<!-- bmn:harness claude gemini -->\nx\n<!-- /bmn:harness -->', 1],
    ['an unclosed section', 'a\n<!-- bmn:shareable -->\nx', 2],
    ['a nested marker', '<!-- bmn:shareable -->\n<!-- bmn:harness codex -->\nx\n<!-- /bmn:harness -->\n<!-- /bmn:shareable -->', 2],
    ['a duplicate team placeholder', '<!-- bmn:team -->\n<!-- bmn:team -->', 2],
    ['a closing marker without an opening one', 'x\n<!-- /bmn:harness -->', 2],
    ['an unrecognised marker', '<!-- bmn:secret -->', 1]
  ])('refuses %s with its line', (_name, text, line) => {
    const { errors } = parseMaster(text)
    expect(errors.length).toBeGreaterThan(0)
    expect(errors.map((error) => error.line)).toContain(line)
  })

  it('renders full for High routes, restricted for Low ones, with header, frontmatter and the team', () => {
    const master = readMaster()
    const approved = generation()
    const codex = render(master, 'codex', approved)
    expect(codex.restricted).toBe(false)
    expect(codex.text.split('\n')[0]).toBe(`> Generated by BMN from ${join(home, '.config/bmn/agents/global-rules.md')} (master sha256 ${sha256(MASTER)}); edit the master, not this file.`)
    expect(codex.text).toContain('PRIVATE-SENTINEL')
    expect(codex.text).not.toContain('OpenCode-only rule')
    expect(codex.text).not.toContain('<!--')
    expect(codex.text).toContain('- Luna: squire, codex, roles helper, focused-reviewer, browser, pre-reviewer, project-pre-reviewer, security high')
    expect(codex.text).not.toContain('Sonnet') // proposed
    expect(codex.text).not.toContain('GLM') // disabled
    expect(codex.text).toContain('Ask `bmn team` for details.')
    const opencode = render(master, 'opencode', approved)
    expect(opencode).toMatchObject({ restricted: true, reason: 'Low route' })
    expect(opencode.text).toContain('Answer first, plainly.')
    expect(opencode.text).not.toContain('PRIVATE-SENTINEL')
    expect(opencode.text).not.toContain('Plain rule for everyone')
    const cursor = render(master, 'cursor', approved)
    expect(cursor.text.startsWith('---\ndescription: ')).toBe(true)
    expect(cursor.text).toContain('alwaysApply: true\n---\n> Generated by BMN')
    expect(cursor.reason).toBe('owner-declared Low route')
    // Nothing shareable: never an empty file, so OpenCode cannot fall back to ~/.claude/CLAUDE.md.
    const bare = render({ ...master, parts: master.parts.filter((part: { kind: string }) => part.kind !== 'shareable') }, 'opencode', approved)
    expect(bare.text).toContain('marked none of them shareable')
  })

  it('shortens the team expansion to fit, then falls back to the pointer', () => {
    const approved = generation()
    expect(teamExpansion(approved).form).toBe('full')
    const many = (count: number, nameLength: number) => ({
      ...approved,
      data: { ...approved.data, agents: Array.from({ length: count }, (_, index) => ({ ...approved.data.agents[0], id: `a${index}`, name: `${'N'.repeat(nameLength)}${index}`, roles: ['lead', 'helper', 'focused-reviewer', 'browser'] })) }
    })
    const shortened = teamExpansion(many(14, 20))
    expect(shortened.form).toBe('without roles')
    expect(Buffer.byteLength(shortened.text)).toBeLessThanOrEqual(TEAM_LIMIT_BYTES)
    const pointer = teamExpansion(many(40, 30))
    expect(pointer).toEqual({ form: 'pointer only', text: 'Ask `bmn team` for details.' })
    expect(teamExpansion(null).form).toBe('pointer (nothing approved)')
  })
})

describe('check (60.4 AC2)', () => {
  it('reports one state per target by precedence', () => {
    mkdirSync(join(home, '.claude'), { recursive: true })
    writeFileSync(target.claude(), 'owner wrote this')
    mkdirSync(join(home, '.codex'), { recursive: true })
    symlinkSync(target.claude(), target.codex())
    mkdirSync(target.cursor(), { recursive: true })
    const states = Object.fromEntries(checkTargets(env).map((entry: { harness: string; state: string }) => [entry.harness, entry.state]))
    expect(states).toEqual({ claude: 'unmanaged', codex: 'link', opencode: 'missing', cursor: 'unreadable' })
  })

  it('reaches current after install, edited-outside after an edit, stale after a master change', async () => {
    expect((await installRules(['claude', 'codex', 'opencode', 'cursor'], { yes: true, environment: env })).code).toBe('OK')
    expect(checkTargets(env).every((entry: { state: string }) => entry.state === 'current')).toBe(true)
    writeFileSync(target.codex(), `${readFileSync(target.codex(), 'utf8')}an outside line\n`)
    writeMasterFile(MASTER.replace('Plain rule for everyone.', 'Plain rule, changed.'))
    const states = Object.fromEntries(checkTargets(env).map((entry: { harness: string; state: string }) => [entry.harness, entry.state]))
    // Every rendering names the master hash in its header, so a master edit makes each one stale.
    expect(states).toEqual({ claude: 'stale', codex: 'edited-outside', opencode: 'stale', cursor: 'stale' })
  })
})

describe('install transactions and restore (60.4 AC3-AC4)', () => {
  it('writes regular files over a link (referent unchanged), an unmanaged and a missing target, and rolls all back', async () => {
    const dotfiles = join(home, 'dotfiles-rules.md')
    writeFileSync(dotfiles, 'shared rules in a dotfiles repo')
    mkdirSync(join(home, '.claude'))
    symlinkSync(dotfiles, target.claude())
    mkdirSync(join(home, '.codex'))
    writeFileSync(target.codex(), 'hand-written codex rules')
    const result = await installRules(['claude', 'codex', 'opencode'], { yes: true, environment: env })
    expect(result.code, JSON.stringify(result)).toBe('OK')
    expect(lstatSync(target.claude()).isFile()).toBe(true)
    expect(readFileSync(dotfiles, 'utf8')).toBe('shared rules in a dotfiles repo')
    expect(readFileSync(target.opencode(), 'utf8')).not.toContain('PRIVATE-SENTINEL')
    const restored = await restoreTransaction(result.transaction!, { yes: true })
    expect(restored).toEqual({ code: 'OK', restored: ['claude', 'codex', 'opencode'] })
    expect(readlinkSync(target.claude())).toBe(dotfiles)
    expect(readFileSync(target.codex(), 'utf8')).toBe('hand-written codex rules')
    expect(existsSync(target.opencode())).toBe(false)
    expect(Object.keys(JSON.parse(readFileSync(join(home, '.config/bmn/agents/state/rules/last-written.json'), 'utf8')))).toEqual([])
  })

  it('names an edited-outside replacement and offers its lines to fold in, never editing the master', async () => {
    await installRules(['codex'], { yes: true, environment: env })
    writeFileSync(target.codex(), `${readFileSync(target.codex(), 'utf8')}Owner added this rule by hand.\n`)
    const result = await runCli(['rules', 'install', 'codex', '--yes'])
    expect(result.code, result.stderr).toBe(0)
    expect(result.stderr).toContain('replaces a file edited outside BMN')
    expect(result.stderr).toContain('    Owner added this rule by hand.')
    expect(readFileSync(join(home, '.config/bmn/agents/global-rules.md'), 'utf8')).toBe(MASTER)
  })

  it('refuses a full rendering when the route changed', async () => {
    const result = await installRules(['codex'], { yes: true, environment: { ...env, OPENAI_BASE_URL: 'https://proxy.example.test/v1' } })
    expect(result.code).toBe('ROUTE_CHANGED')
    expect(existsSync(target.codex())).toBe(false)
  })

  it('stops after a failure, keeps the manifest and restores what changed', async () => {
    mkdirSync(join(home, '.claude'))
    symlinkSync(join(home, 'elsewhere.md'), target.claude())
    const result = await installRules(['claude', 'codex', 'opencode'], { yes: true, environment: env, beforeTarget: (_harness: string, index: number) => { if (index === 2) throw new Error('disk full') } })
    expect(result).toMatchObject({ code: 'INSTALL_FAILED', written: [{ harness: 'claude' }, { harness: 'codex' }] })
    expect(existsSync(target.opencode())).toBe(false)
    expect((await restoreTransaction(result.transaction!, { yes: true })).code).toBe('OK')
    expect(readlinkSync(target.claude())).toBe(join(home, 'elsewhere.md'))
    expect(existsSync(target.codex())).toBe(false)
  })

  it('plans again after the confirmation and writes nothing when the plan changed meanwhile', async () => {
    const result = await installRules(['codex'], { yes: true, environment: env,
      afterConfirm: () => writeMasterFile(MASTER.replace('Plain rule for everyone.', 'Changed while the owner read the diff.')) })
    expect(result).toMatchObject({ code: 'REVISION_CONFLICT', transaction: null, written: [] })
    expect(existsSync(target.codex())).toBe(false)
    expect(existsSync(join(home, '.config/bmn/agents/state/rules/transactions'))).toBe(false)
  })

  it('needs a TTY or --yes, and writes nothing otherwise', async () => {
    const result = await runCli(['rules', 'install', 'codex'])
    expect(result.code).toBe(1)
    expect(result.stderr).toContain('CONFIRMATION_REQUIRED')
    expect(existsSync(target.codex())).toBe(false)
  })
})

describe('master history (60.4 AC4)', () => {
  it('lists source snapshots and writes one back as a new revision', async () => {
    await installRules(['codex'], { yes: true, environment: env })
    const changed = MASTER.replace('Plain rule for everyone.', 'Plain rule, second version.')
    writeMaster({ kind: 'file', text: MASTER, mode: 0o644 }, changed, 'panel save')
    expect(masterHistory().map((entry: { revision: number; reason: string }) => [entry.revision, entry.reason])).toEqual([[1, expect.stringMatching(/^install /)], [2, 'panel save']])
    const reverted = await runCli(['rules', 'revert-master', '1', '--yes'])
    expect(reverted.code, reverted.stderr).toBe(0)
    expect(readFileSync(join(home, '.config/bmn/agents/global-rules.md'), 'utf8')).toBe(MASTER)
    // Reverting to an identical source adds no duplicate snapshot; a rendering is never a snapshot.
    expect(masterHistory().every((entry: { hash: string }) => entry.hash !== sha256(readFileSync(target.codex(), 'utf8')))).toBe(true)
  })

  it('exits 13 and writes nothing when history is absent or corrupt', async () => {
    expect((await runCli(['rules', 'history'])).code).toBe(13)
    await installRules(['codex'], { yes: true, environment: env })
    writeFileSync(join(home, '.config/bmn/agents/state/rules/master-history/index.json'), '{not json')
    const before = readFileSync(join(home, '.config/bmn/agents/global-rules.md'), 'utf8')
    expect((await runCli(['rules', 'revert-master', '1', '--yes'])).code).toBe(13)
    expect(readFileSync(join(home, '.config/bmn/agents/global-rules.md'), 'utf8')).toBe(before)
  })

  it('keeps a master edited outside BMN as a snapshot before a save replaces it', async () => {
    await installRules(['codex'], { yes: true, environment: env })
    const outside = MASTER.replace('Plain rule for everyone.', 'Edited by hand, never snapshotted.')
    writeMasterFile(outside)
    writeMaster({ kind: 'file', text: outside, mode: 0o644 }, MASTER.replace('Plain rule for everyone.', 'Saved from the panel.'), 'panel save')
    const history = masterHistory()
    expect(history.map((entry: { reason: string }) => entry.reason)).toEqual([expect.stringMatching(/^install /), 'before panel save', 'panel save'])
    expect(history[1]?.hash).toBe(sha256(outside))
  })

  it('refuses a save before writing when the history cannot record the text it replaces', async () => {
    await installRules(['codex'], { yes: true, environment: env })
    writeFileSync(join(home, '.config/bmn/agents/state/rules/master-history/index.json'), '{not json')
    expect(() => writeMaster({ kind: 'file', text: MASTER, mode: 0o644 }, MASTER.replace('Plain', 'New'), 'panel save')).toThrow(/history/)
    expect(readFileSync(join(home, '.config/bmn/agents/global-rules.md'), 'utf8')).toBe(MASTER)
  })

  it('refuses to write a master that would not render', () => {
    expect(() => writeMaster({ kind: 'file', text: MASTER, mode: 0o644 }, '<!-- bmn:shareable -->\nunclosed', 'bad')).toThrow(/would not render/)
    expect(readFileSync(join(home, '.config/bmn/agents/global-rules.md'), 'utf8')).toBe(MASTER)
  })
})

describe('CLI (60.4)', () => {
  it('render prints the exact file and names its form; a missing or invalid master exits 3 or 4 before any target', async () => {
    const rendered = await runCli(['rules', 'render', 'opencode'])
    expect(rendered.code).toBe(0)
    expect(rendered.stdout).toBe(render(readMaster(), 'opencode', generation()).text)
    expect(rendered.stderr).toContain('restricted rendering (Low route); team: full')
    expect((await runCli(['rules', 'render', 'gemini'])).code).toBe(4)
    writeMasterFile('<!-- bmn:shareable -->\nunclosed')
    const invalid = await runCli(['rules', 'check', '--json'])
    expect(invalid.code).toBe(4)
    expect(JSON.parse(invalid.stdout).errors[0].line).toBe(1)
    rmSync(join(home, '.config/bmn/agents/global-rules.md'))
    expect((await runCli(['rules', 'check'])).code).toBe(3)
  })

  it('imports today\'s rules once, with the team placeholder and an opencode section', async () => {
    rmSync(join(home, '.config/bmn/agents/global-rules.md'))
    const source = '# Global rules\n\n## Team\nThe team: A, B and C.\n\n## Other\nrule\n'
    expect(importedMaster(source, '## OpenCode\n- use the guardrails\n')).toBe(
      '# Global rules\n\n## Team\nThe team: A, B and C.\n\n<!-- bmn:team -->\n\n## Other\nrule\n\n<!-- bmn:harness opencode -->\n## OpenCode\n- use the guardrails\n<!-- /bmn:harness -->\n')
    writeFileSync(join(home, 'claude-rules.md'), source)
    const imported = await runCli(['rules', 'import', '--from', join(home, 'claude-rules.md'), '--yes'])
    expect(imported.code, imported.stderr).toBe(0)
    expect((await runCli(['rules', 'import', '--from', join(home, 'claude-rules.md'), '--yes'])).code).toBe(7)
  })
})

function runCli(args: string[], extra: Record<string, string> = {}): Promise<{ code: number | null; stdout: string; stderr: string }> {
  return new Promise((resolve) => {
    const child = execFile(process.execPath, [CLI, ...args], { env: { ...env, ...extra }, timeout: 20_000 },
      (error, stdout, stderr) => resolve({ code: error === null ? 0 : typeof error.code === 'number' ? error.code : null, stdout, stderr }))
    child.stdin?.end()
  })
}

describe('probes (60.4 AC5)', () => {
  beforeEach(async () => {
    await installRules(['claude', 'codex', 'opencode', 'cursor'], { yes: true, environment: env })
  })

  it('Claude passes when it quotes the rendered hash with tools off, fails on another', async () => {
    stub('claude', `case "$1" in --version) echo "2.1.295 (Claude Code)";; *) cat > /dev/null; grep -o 'master sha256 [0-9a-f]*' "$HOME/.claude/CLAUDE.md" | cut -d' ' -f3;; esac`)
    const result = await probe('claude', { environment: env })
    expect(result).toMatchObject({ outcome: 'pass', version: '2.1.295' })
    stub('claude', 'case "$1" in --version) echo "2.1.295";; *) cat > /dev/null; echo 0000000000000000000000000000000000000000000000000000000000000000;; esac')
    expect((await probe('claude', { environment: env })).outcome).toBe('fail')
    stub('claude', 'case "$1" in --version) echo "2.1.295";; *) cat > /dev/null; echo "I cannot tell";; esac')
    expect((await probe('claude', { environment: env })).outcome).toBe('inconclusive')
  })

  it('Codex reads the injected instructions from its own probe rollout', async () => {
    stub('codex', `case "$1" in --version) echo "codex-cli 0.161.0";; exec) cwd="$4"; d="$HOME/.codex/sessions/2026/10/09"; mkdir -p "$d"; cat > /dev/null
      printf '{"type":"session_meta","payload":{"cwd":"%s"}}\\n{"type":"instructions","text":"%s"}\\n' "$cwd" "$(head -1 "$HOME/.codex/AGENTS.md" | sed 's/"/ /g')" > "$d/rollout-probe.jsonl";; esac`)
    expect(await probe('codex', { environment: env })).toMatchObject({ outcome: 'pass', version: '0.161.0', host: expect.any(String) })
    expect(lastProbes().find((entry: { harness: string }) => entry.harness === 'codex')).toMatchObject({ outcome: 'pass', stale: false })
    writeMasterFile(MASTER.replace('Plain rule for everyone.', 'Changed.'))
    expect(lastProbes().find((entry: { harness: string }) => entry.harness === 'codex')).toMatchObject({ stale: true })
  })

  it('a hash the rollout shows only after a tool ran is no evidence: the agent may have read the file', async () => {
    stub('codex', `case "$1" in --version) echo "codex-cli 0.161.0";; exec) cwd="$4"; d="$HOME/.codex/sessions/2026/10/09"; mkdir -p "$d"; cat > /dev/null
      printf '{"type":"session_meta","payload":{"cwd":"%s"}}\\n{"type":"response_item","payload":{"type":"function_call","name":"shell"}}\\n{"type":"response_item","payload":{"type":"function_call_output","output":"%s"}}\\n' "$cwd" "$(head -1 "$HOME/.codex/AGENTS.md" | sed 's/"/ /g')" > "$d/rollout-probe.jsonl";; esac`)
    expect(await probe('codex', { environment: env })).toMatchObject({ outcome: 'fail', detail: expect.stringContaining('before any tool ran') })
  })

  it('reinspects the destination before sending and refuses when it moved; nothing runs', async () => {
    stub('codex', `case "$1" in --version) echo "codex-cli 0.161.0";; *) touch "$HOME/codex-ran";; esac`)
    const moved = await probe('codex', { environment: { ...env, OPENAI_BASE_URL: 'https://proxy.example.test/v1' } })
    expect(moved).toMatchObject({ outcome: 'unavailable', detail: expect.stringContaining('refused') })
    expect(existsSync(join(home, 'codex-ran'))).toBe(false)
  })

  it('an earlier probe is stale once the harness version or its destination changes', async () => {
    stub('claude', `case "$1" in --version) echo "2.1.295 (Claude Code)";; *) cat > /dev/null; grep -o 'master sha256 [0-9a-f]*' "$HOME/.claude/CLAUDE.md" | cut -d' ' -f3;; esac`)
    const passed = await probe('claude', { environment: env })
    const claude = (inspect: (harness: string) => { version: string | null; host: string | null }): unknown =>
      lastProbes({ inspect }).find((entry: { harness: string }) => entry.harness === 'claude')
    const host = passed.host ?? null
    expect(claude(() => ({ version: '2.1.295', host }))).toMatchObject({ stale: false })
    expect(claude(() => ({ version: '2.1.296', host }))).toMatchObject({ stale: true })
    expect(claude(() => ({ version: '2.1.295', host: 'proxy.example.test' }))).toMatchObject({ stale: true })
  })

  it('a probe goes stale through the app\'s own version inspector once the harness that runs is replaced', async () => {
    const shadow = join(home, 'shadow')
    mkdirSync(shadow)
    writeFileSync(join(shadow, 'claude'), 'not a program\n', { mode: 0o644 })
    const environment = { ...env, PATH: `${shadow}:${env.PATH}` }
    stub('claude', `case "$1" in --version) echo "2.1.295 (Claude Code)";; *) cat > /dev/null; grep -o 'master sha256 [0-9a-f]*' "$HOME/.claude/CLAUDE.md" | cut -d' ' -f3;; esac`)
    expect(await probe('claude', { environment })).toMatchObject({ outcome: 'pass' })
    const claude = async (): Promise<unknown> => lastProbes({ inspect: await probeInspector(environment) }).find((entry: { harness: string }) => entry.harness === 'claude')
    expect(await claude()).toMatchObject({ stale: false })
    rmSync(join(stubs, 'claude'))
    stub('claude', 'case "$1" in --version) echo "2.1.296 (Claude Code)";; esac')
    expect(await claude()).toMatchObject({ stale: true })
  })

  it('is unavailable for a Low route or a missing CLI, and leaves no throwaway folder', async () => {
    stub('opencode', 'echo "1.18.32"')
    expect(await probe('opencode', { environment: env })).toMatchObject({ outcome: 'unavailable', detail: expect.stringContaining('not High') })
    expect((await probe('cursor', { environment: env })).outcome).toBe('unavailable')
    expect(readFileSync(join(home, '.config/bmn/agents/state/probes.jsonl'), 'utf8').split('\n').filter(Boolean)).toHaveLength(2)
    expect(existsSync(join(home, '.bmn-rules-probe-'))).toBe(false)
  })
})

describe('the panel binds install and restore to the plan it showed (60.6 AC4)', () => {
  it('a plan names each target\'s change; a stale plan hash writes nothing; the shown one installs and restores', async () => {
    mkdirSync(join(home, 'dotfiles'))
    writeFileSync(join(home, 'dotfiles/CLAUDE.md'), '# kept elsewhere\n')
    mkdirSync(join(home, '.claude'))
    symlinkSync(join(home, 'dotfiles/CLAUDE.md'), target.claude())
    mkdirSync(join(home, '.codex'))
    writeFileSync(target.codex(), '# by hand\n')
    const planned = await runCli(['rules', 'install', '--plan', '--json'])
    const plan = JSON.parse(planned.stdout)
    expect(plan.code).toBe('OK')
    expect(Object.fromEntries(plan.targets.map((entry: { harness: string; change: string }) => [entry.harness, entry.change])))
      .toEqual({ claude: 'link', codex: 'unmanaged', opencode: 'missing', cursor: 'missing' })
    expect(existsSync(target.opencode())).toBe(false)

    writeFileSync(target.codex(), '# by hand, changed after the plan was shown\n')
    const stale = JSON.parse((await runCli(['rules', 'install', '--expect-plan', plan.plan_hash, '--yes', '--json'])).stdout)
    expect(stale.code).toBe('REVISION_CONFLICT')
    expect(lstatSync(target.claude()).isSymbolicLink()).toBe(true)
    expect(existsSync(target.opencode())).toBe(false)

    const fresh = JSON.parse((await runCli(['rules', 'install', '--plan', '--json'])).stdout)
    const installed = JSON.parse((await runCli(['rules', 'install', '--expect-plan', fresh.plan_hash, '--yes', '--json'])).stdout)
    expect(installed.code).toBe('OK')
    expect(lstatSync(target.claude()).isSymbolicLink()).toBe(false)
    expect(readFileSync(join(home, 'dotfiles/CLAUDE.md'), 'utf8')).toBe('# kept elsewhere\n')

    const restorePlan = JSON.parse((await runCli(['rules', 'restore', '--transaction', installed.transaction, '--plan', '--json'])).stdout)
    expect(restorePlan.targets.find((entry: { harness: string }) => entry.harness === 'claude').change).toBe('link')
    expect((await runCli(['rules', 'restore', '--transaction', installed.transaction, '--expect-plan', '0'.repeat(64), '--yes', '--json'])).stdout)
      .toContain('REVISION_CONFLICT')
    const restored = await runCli(['rules', 'restore', '--transaction', installed.transaction, '--expect-plan', restorePlan.plan_hash, '--yes', '--json'])
    expect(JSON.parse(restored.stdout).code).toBe('OK')
    expect(readlinkSync(target.claude())).toBe(join(home, 'dotfiles/CLAUDE.md'))
    expect(readFileSync(target.codex(), 'utf8')).toBe('# by hand, changed after the plan was shown\n')
  })
})
